package it.polimi.ingsw.controller;

public enum EndOfGameReason {
    LAST_TOWER_BUILD,
    THREE_ISLANDS_REMAINING_TOWER,
    THREE_ISLANDS_REMAINING_PROFESSOR,
    THREE_ISLANDS_REMAINING_TIE,
    LAST_ROUND_TOWER,
    LAST_ROUND_PROFESSOR,
    LAST_ROUND_TIE
}
